Ndarrays, Indexing, and Slicing

In [15]:
#Start by importing the numpy and pandas library

import numpy as np
import pandas as pd

#Try creating a 4 row x 4 column array of integers
int_ar1 = np.ones((4,4), dtype = int)
int_ar1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
#let's try altering this array. First, let's save a sopy of this array
int_ar2 = int_ar1.copy()

In [17]:
#Next, let's change the entire first row to twos (2)
int_ar2[0,:] = np.ones(4, dtype = int)*2
int_ar2

array([[2, 2, 2, 2],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
#With some for loops, we can more dynamically change our arrays. 
# Change the diagonal to a new number.
np.fill_diagonal(int_ar2, 10)
int_ar2


array([[10,  2,  2,  2],
       [ 1, 10,  1,  1],
       [ 1,  1, 10,  1],
       [ 1,  1,  1, 10]])

In [19]:
#We can also change the contents of an array through arithmetic procedures.
# Multiply the values by some number.
int_ar2*2

array([[20,  4,  4,  4],
       [ 2, 20,  2,  2],
       [ 2,  2, 20,  2],
       [ 2,  2,  2, 20]])

In [20]:
int_ar2 - 5

array([[ 5, -3, -3, -3],
       [-4,  5, -4, -4],
       [-4, -4,  5, -4],
       [-4, -4, -4,  5]])

Arrays and Matrices

In [22]:
#Confirm that the array is 4x4
#Remembers, arrays are given by ----> # of rows X # of columns.
int_ar2.shape

(4, 4)

In [24]:
#Okay, now try and create a 5 x 5 array of ones
float_ar1 = np.ones((5,5))
float_ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#Create 3 identity matrices of any size
eye_ar1 = np.eye(2)
eye_ar2 = np.eye(3)
eye_ar3 = np.eye(4)

In [26]:
eye_ar1

array([[1., 0.],
       [0., 1.]])

In [27]:
eye_ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
eye_ar3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Quick List Comprehension/Lambda function Exercises

In [11]:
# 1
# make a list comprehension which filters the even numbers 
#out of the following numpy array: np.arange(1,100,3)

In [30]:
[x for x in np.arange(1,100,3) if x%2]

[1, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97]

In [42]:
# 2 for the following mispelled list of Beatles, write a function correct_beatles,
# then use the built-in map function to create a corrected list of Beatles.

beatle_list = ['John', 'Rango', 'Pal', 'Geoge', 
               'Rungo', 'Gage', 'Pul', 'Jonathan', 'Mike']

def correct_beatles(name):
    beatle_dict = {'J': 'John', 'R': 'Ringo', 'P': 'Paul', 'G': 'George'}
    
    for letter in beatle_dict:
        if(name.startswith(str(letter))):
            name = beatle_dict[letter]
            break
    #If the name ends up not being close to one of the Beatle members, change it to a random Beatle member
    if(name not in list(beatle_dict.values())):
        name = np.random.choice(['Paul', 'Ringo', 'George', 'John'], 1 , replace = False)[0]
            
    return name
        
correct_list = map(correct_beatles, beatle_list)
print(list(correct_list))

['John', 'Ringo', 'Paul', 'George', 'Ringo', 'George', 'Paul', 'John', 'Ringo']
